### ISSUE TITLE
The screen is on, but it says it's not

### ISSUE THREAD

**Issue by deany1014** [Mysticpasta1/webdisplays#12]
![image](https://github.com/CinemaMod/webdisplays/assets/136552279/877df835-5c1f-482e-a1e2-106b58234801)

**Comment by GiantLuigi4** [comment]
1.18?

If so, it should be one of the corners, and you may have to click on the back

Though I can’t guarantee that the GUI will work, and also can’t guarantee that you’ll be able to close it

**Comment by deany1014** [comment]
> 1.18?
> 
> If so, it should be one of the corners, and you may have to click on the back
> 
> Though I can’t guarantee that the GUI will work, and also can’t guarantee that you’ll be able to close it

No, version 1.20.1

**Comment by GiantLuigi4** [comment]
Turns out the screen configuration doesn't work on screens facing east, down, or up

I'll have to look into that I guess

**Comment by GiantLuigi4** [comment]
ohh wait

no I'm wrong on that, and I think I know why it's broken

It seems to be using the player's approximate facing direction instead of the side clicked

Yep, will be fixed next version 
![image](https://github.com/CinemaMod/webdisplays/assets/49770992/08fa414d-4b6a-4df8-8501-74ffa84f4f17)

**Comment by deany1014** [comment]
webdisplays:ownerthief also does not work, same issue it thinks the screen is off
